### ISSUE TITLE
Tagger web API returns error 500

### ISSUE THREAD

**Issue by kalev** [fedora-infra/fedora-tagger#194]
```
$ curl https://apps.fedoraproject.org/tagger/api/v1/simple-scan/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Same error when uploading ratings.

**Comment by ralphbean** [comment]
Here's the associated traceback:

```python
[Mon Sep 14 14:04:29.147589 2015] [:error] [pid 30321] ERROR:fedoratagger:Exception on /api/v1/simple-scan/ [GET]
[Mon Sep 14 14:04:29.147685 2015] [:error] [pid 30321] Traceback (most recent call last):
[Mon Sep 14 14:04:29.147705 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Mon Sep 14 14:04:29.147717 2015] [:error] [pid 30321]     response = self.full_dispatch_request()
[Mon Sep 14 14:04:29.147727 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Mon Sep 14 14:04:29.147737 2015] [:error] [pid 30321]     rv = self.handle_user_exception(e)
[Mon Sep 14 14:04:29.147745 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Mon Sep 14 14:04:29.147751 2015] [:error] [pid 30321]     reraise(exc_type, exc_value, tb)
[Mon Sep 14 14:04:29.147757 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Mon Sep 14 14:04:29.147762 2015] [:error] [pid 30321]     rv = self.dispatch_request()
[Mon Sep 14 14:04:29.147767 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Mon Sep 14 14:04:29.147772 2015] [:error] [pid 30321]     return self.view_functions[rule.endpoint](**req.view_args)
[Mon Sep 14 14:04:29.147777 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/fedoratagger/api/api.py", line 510, in pkg
[Mon Sep 14 14:04:29.147782 2015] [:error] [pid 30321]     return pkg_get(pkgname)
[Mon Sep 14 14:04:29.147810 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/fedoratagger/api/api.py", line 67, in pkg_get
[Mon Sep 14 14:04:29.147816 2015] [:error] [pid 30321]     jsonout = flask.jsonify(output)
[Mon Sep 14 14:04:29.147821 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/flask/json.py", line 238, in jsonify
[Mon Sep 14 14:04:29.147827 2015] [:error] [pid 30321]     indent=indent),
[Mon Sep 14 14:04:29.147832 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
[Mon Sep 14 14:04:29.147837 2015] [:error] [pid 30321]     rv = _json.dumps(obj, **kwargs)
[Mon Sep 14 14:04:29.147842 2015] [:error] [pid 30321]   File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 369, in dumps
[Mon Sep 14 14:04:29.147847 2015] [:error] [pid 30321]     **kw).encode(obj)
[Mon Sep 14 14:04:29.147851 2015] [:error] [pid 30321]   File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 264, in encode
[Mon Sep 14 14:04:29.147856 2015] [:error] [pid 30321]     chunks = list(chunks)
[Mon Sep 14 14:04:29.147861 2015] [:error] [pid 30321]   File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 612, in _iterencode
[Mon Sep 14 14:04:29.147866 2015] [:error] [pid 30321]     for chunk in _iterencode_dict(o, _current_indent_level):
[Mon Sep 14 14:04:29.147871 2015] [:error] [pid 30321]   File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 568, in _iterencode_dict
[Mon Sep 14 14:04:29.147876 2015] [:error] [pid 30321]     for chunk in chunks:
[Mon Sep 14 14:04:29.147881 2015] [:error] [pid 30321]   File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 622, in _iterencode
[Mon Sep 14 14:04:29.147886 2015] [:error] [pid 30321]     o = _default(o)
[Mon Sep 14 14:04:29.147890 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/flask_fas_openid.py", line 80, in default
[Mon Sep 14 14:04:29.147895 2015] [:error] [pid 30321]     return flask.json.JSONEncoder.default(self, o)
[Mon Sep 14 14:04:29.147900 2015] [:error] [pid 30321]   File "/usr/lib/python2.7/site-packages/flask/json.py", line 83, in default
[Mon Sep 14 14:04:29.147905 2015] [:error] [pid 30321]     return _json.JSONEncoder.default(self, o)
[Mon Sep 14 14:04:29.147910 2015] [:error] [pid 30321]   File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 239, in default
[Mon Sep 14 14:04:29.147915 2015] [:error] [pid 30321]     raise TypeError(repr(o) + " is not JSON serializable")
[Mon Sep 14 14:04:29.147921 2015] [:error] [pid 30321] TypeError: <bound method Package.icon of <fedoratagger.lib.model.Package object at 0x7f0ab6f7a650>> is not JSON serializable
```
